# Generated by Django 2.2.3 on 2019-10-02 03:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('Contact', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('id', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(default='', max_length=150)),
                ('File', models.FileField(upload_to='upload/')),
                ('operation', models.CharField(choices=[('1', 'Simple Thresholding'), ('2', 'Adaptive-mean Thresholding'), ('3', 'Gaussian-mean Thresholding'), ('4', 'Otsu Thresholding')], default='1', max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr_app.Upload')),
            ],
        ),
    ]
