# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default=b'', max_length=250)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'Email Address')),
                ('Contact', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('id', 'email')]),
        ),
    ]
