# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-07 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Contact',
            field=models.IntegerField(null=True),
        ),
    ]
