# Generated by Django 2.2.3 on 2019-07-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0003_auto_20190707_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
