# Generated by Django 2.2.3 on 2019-07-23 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0005_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configName', models.CharField(max_length=200)),
                ('inputFolder', models.FilePathField(allow_files=False, allow_folders=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
