# Generated by Django 2.2.3 on 2019-07-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0006_fileconf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileConf',
            new_name='FileConfig',
        ),
    ]
