# Generated by Django 2.2.3 on 2019-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0007_auto_20190723_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileconfig',
            name='operation',
            field=models.CharField(choices=[(1, 'Simple Thresholding'), (2, 'Adaptive-mean Thresholding'), (3, 'Gaussian-mean Thresholding'), (4, 'Otsu Thresholding')], default=1, max_length=150),
        ),
        migrations.AddField(
            model_name='fileconfig',
            name='outputFolder',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fileconfig',
            name='processFolder',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileconfig',
            name='configName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fileconfig',
            name='inputFolder',
            field=models.TextField(default='', max_length=255),
        ),
    ]
