# Generated by Django 2.2.3 on 2019-07-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0008_auto_20190723_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileconfig',
            name='operation',
            field=models.CharField(choices=[('1', 'Simple Thresholding'), ('2', 'Adaptive-mean Thresholding'), ('3', 'Gaussian-mean Thresholding'), ('4', 'Otsu Thresholding')], default='1', max_length=150),
        ),
    ]
