# Generated by Django 2.2.3 on 2019-08-10 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0010_auto_20190724_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(default='', max_length=150)),
                ('File', models.FileField(upload_to='media/upload/')),
                ('operation', models.CharField(choices=[('1', 'Simple Thresholding'), ('2', 'Adaptive-mean Thresholding'), ('3', 'Gaussian-mean Thresholding'), ('4', 'Otsu Thresholding')], default='1', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FileConfig',
        ),
    ]
