# Generated by Django 2.2.3 on 2019-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0011_auto_20190810_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='File',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
